# name of the software
name: jQCloud
# current version of the software
version: 2.0.3
# url of the download button
downloadUrl: https://github.com/mistic100/jQCloud
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

# list of additional links on the right of the top menu
headerLinks:
  - title: StrangePlanet
    url: http://www.strangeplanet.fr
  - title: GitHub
    url: https://github.com/mistic100/jQCloud

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/mistic100/jQCloud
  - title: Issues
    url: https://github.com/mistic100/jQCloud/issues?state=open
  - title: StrangePlanet
    url: http://www.strangeplanet.fr

# header
header:
  color1: "#00E5BC"
  color2: "#00B4E0"
  trianglify: true

# github buttons
githubButton:
  user: mistic100
  repo: jQCloud

# twitter buttons
twitter:
  enabled: true
  via: mistic100
  hash:
  account:

# facebook buttons
facebook:
  enabled: true
  profileUrl:

# google analytics
analytics:
  account: UA-28192323-3
  domain: mistic100.github.io


exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'bower.json']